services:
  server:
    image: ghcr.io/devgianlu/go-fileshare:latest
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./data:/data
      - ./server.example.yml:/server.yml:ro